name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Cambia a master si usas esa rama

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build # Asegúrate de que el base-path en vite.config sea './'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # O 'build' si usas Create React App
          branch: gh-pages
